spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
      name: applicationaaaaaaaaaaa-2
server:
  port: 11001
---
spring:
  profiles: test #测试环境
  application:
    name: applicationbbbbbbbbbbbbb-2
server:
  port: 11000
